# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U3bvpeW-TN7UNGsZS8wi4j0-lJFFv0Nl
"""

def print_nama_kel_Jatim(mantee):
    for nama in mantee:
        print(nama)

# Contoh list nama orang
daftar_nama = ["Pangestu Sandya Etniko Siagian",
               "Name",
               "Auditi Kurnia Wijayanti",
               "Name",
               "Name"]

# Memanggil fungsi untuk memprint nama orang
print_nama_kel_Jatim(daftar_nama)
